### ISSUE TITLE
Error: Python shared library not found, Python bindings not loaded

### ISSUE THREAD

**Issue by ShirleyJenniferSerranoRojas** [tobiashofmann88/iucnsim#2]
Hi,
Thank you for sharing this great package.
I am following the installation in R studio, but for some reason that I don't understand after running the line:
reticulate::source_python("https://raw.githubusercontent.com/tobiashofmann88/iucn_extinction_simulator/master/iucn_sim/iucn_sim.py")
It gives me the next error:
Error: Python shared library not found, Python bindings not loaded.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.

I can't find a way to fix this. Do you have any suggestions?
Thank you so much

**Comment by tandermann** [comment]
Does it work after running `reticulate::install_miniconda()` in the R console? Seems like the miniconda environment did not install properly. Which system are you running this on (Mac, Windows, or Linux)?

**Comment by ShirleyJenniferSerranoRojas** [comment]
Yes, thank you so much, it worked in the terminal following your tutorial. I am running this on a Mac, which I am just learning to use as well. I am working with amphibian data. Do you have any advice on how to obtain information on the generation length for amphibians? Thank you so much
